README.md
mysite/sample.env
requirements.txt

Please reply if this can setup the project on your local machine on not.
I will upload the instruction in README.md soon.

setup the project in dev team

---

foods/templates/foods/detail.html
foods/templates/foods/index.html
foods/urls.py
foods/views.py
mysite/sample.env
mysite/settings.py

I write the sample template in detail.html
modify soon.

Access the detail page by menu id

---

foods/templates/foods/base.html
foods/templates/foods/index.html

TMR I'll do [search bar] and [drop drown bar] 🤩
also find the way to add logo to nav bar w/out error😤

add new navbar to detail page

---

foods/static/foods/style.css
foods/templates/foods/base.html
foods/templates/foods/navbar.html
foods/templates/foods/search_bar.html
foods/urls.py
foods/views.py

I'll done all Navbar function bar tmr.

Separate function and add initial search bar

---

foods/admin.py
foods/get_data.py
foods/static/foods/style.css
foods/templates/foods/base.html
foods/templates/foods/navbar.html
foods/templates/foods/search_bar.html
foods/views.py
mysite/settings.py
mysite/urls.py
templates/authentication/logout.html

dropdown bar is now can't shown the menu bar and search can't search efficiently something wrong and I need suggest of you guys. I also add initial auth.

add dropdown bar, funtion in search bar, initial auth

---

templates/registration/login.html
templates/registration/signup.html

adding signup page and some decoration.

add signup page

---

foods/urls.py
foods/views.py

I implement caching on index page which need to be loaded frequency.
Caching on time will last for a hour.
Put some rearrange in fetching API helps this page load much Faster.
From now on, we can do work much faster than before!!

Speed of Light load the web interface using Cache!

---

foods/templates/foods/navbar.html
foods/views.py

I Fix the external content button.
It's can be toggle to see inside.
But not yet put the link to other pageห. Because other pages are not in this iteration.
I didn't do much in decoration. Anyway, function is working now.

External content can toggle and show list of pages.

---

foods/templates/foods/navbar.html
templates/registration/login.html
templates/registration/signup.html

decorate login and signup also fix position botton in nav bar

---

foods/templates/foods/detail.html

I didn't do things much but layout the website.
Ordering content user will see when narrowed the screen.
Menu name
Creator name
Picture
Description
Brief information; # of ingredients, total cooking time ,and energy calories.
Ingredients
then, Nutrition
I also removed the divider because on some browser, the divider is lay on the picture and I don't know the solution yet.

Do layout the menu detail.

---

foods/models.py
foods/templates/foods/index.html
foods/views.py

add suggest foods layout

---

foods/admin.py
foods/models.py
foods/templates/foods/index.html
foods/views.py

I fix the bug timezone.now to datetime.datetime.now 
Now the page can be visited and going to do the template suggests food next
1. ```python3 manage.py makemigrations```
2. ```python3 manage.py migrate```
3. ```python3 manage.py dumpdata > data.json```
4. ```python3 manage.py runserver```

Bugfix : datetime.datetime.now()

---

foods/templates/foods/index.html
foods/templates/foods/navbar.html

add search bar suggestion by JavaScript function.

add realtime suggest search bar by filtering

---

foods/templates/foods/detail.html
foods/templates/foods/navbar.html
foods/views.py

search bar can now use efficiently.

:bug:Bug Fixed search bar and add new function to seach bar

---

foods/templates/foods/index.html

Add menu names on menu blocks and fill the background color.
Make blocks hover and make a whole block clickable.

align menu blocks

---

foods/templates/foods/detail.html

Now Nutrition information is show in formatted inline-block.

Modify Nutrition section.

---

foods/views.py

delete old total_cooking_time field

Fix Menu field ERROR

---

foods/models.py
foods/templates/registration/login.html
foods/templates/registration/signup.html
foods/views.py

I recreate auth page and also add some query for filter page also want you to look add that query
and help me find the idea to create the filter page. 
And I need to talk about ui in sign up page too. If you are available pls contract me.🤩

recreate auth page and also add some query for filter page

---

foods/templates/foods/index.html

- Made the background color to cover all the white space below.
- Aligned Food of the Day and menu name vertically.
- Fixed the positions of Food of the Day and menu image.
- Adjusted the space between Food of the Day menu name and menu image.
- Changed the color when hovering over the Food of the Day's menu name (just don't want it to be plain black 😗).
- Removed the underlined link when hovering over menus (those underlined thingy just got on my nerves 🫠).

Improved Food of the Day

---

foods/templates/foods/cookhome.html

Completed My Cookbook page frontend

---

foods/templates/foods/community.html
foods/templates/foods/cookhome.html
foods/templates/foods/createmenu.html
foods/templates/foods/detail.html
foods/templates/foods/index.html
foods/templates/foods/navbar.html
foods/templates/foods/top_foods.html

Everything on Navbar is still the same but with a better look. And some bugs ,which occur when resizing the window, is removed. I also adjusted a little of other page too, such as changing the font, aligning and decorating Top-Rated Dishes page.  However, I still don't be satisfied with the Dropdown Menu on Navbar even though there's nothing wrong with the functionality, which means that there's just something wrong with a little animation 🥴.

NavBar fixed and beautifully decorated :)

---

foods/templates/foods/cookhome.html
foods/templates/foods/navbar.html
foods/templates/foods/top_foods.html

Just a little decoration of Community's Foods page, which was My Cookbook before.

Change from my cookbook to community's foods

---

foods/templates/foods/detail.html

Since the demo last time, I got commented about UX/UI in detail page. I decorate it to be more organized and hope it is easier to read.

Detail page looks more organized

---

foods/templates/foods/cookhome.html
foods/templates/foods/createmenu.html
foods/templates/foods/detail.html
foods/templates/foods/filter_result.html
foods/templates/foods/navbar.html
foods/templates/foods/show_detail.html
foods/templates/foods/top_foods.html

At first, the elements in Top-Rated Dishes page are not centered when the window is resized. Now I fixed it. And of course, with some decorations. The Detail page and also Community's Foods Detail page are now organized. Filtered Results page is fixed and slightly decorated.

Frontend Renovation

---

foods/views.py

can show number of ingredients by users input

🐛 Fix number of ingredients

---

mysite/urls.py

I changed the url for allauth url and set up new redirect url in Google Creditials API already

Use different url for allauth login

---

foods/templates/foods/createmenu.html
foods/templates/foods/detail.html
foods/templates/foods/show_detail.html

Change input of description to textarea on CreateMenu page for a better look :)

Improve CreateMenu page
